kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: {{ingress_http_port}}
        protocol: TCP
      - containerPort: 443
        hostPort: {{ingress_https_port}}
        protocol: TCP
networking:
  kubeProxyMode: "ipvs"

# create a cluster with the local registry enabled in containerd
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:{{reg_port}}"]
    endpoint = ["http://{{reg_name}}:{{reg_port}}"]
