- hosts: all
  become: no
  gather_facts: no
  
  vars:
    proxy_env:
      http_proxy: '{{ lookup("env", "http_proxy") }}'
      https_proxy: '{{ lookup("env", "https_proxy") }}'
      no_proxy: '{{ lookup("env", "no_proxy") }}'

  tasks:
    - name: Check out ChaordicLedger Git repository
      ansible.builtin.git:
        repo: 'https://github.com/lmco/ChaordicLedger.git'
        dest: ~/git/lmco/ChaordicLedger
        version: iac_update
        force: yes

    - name: Copy CA Certificates archive
      ansible.builtin.copy:
        src: ~/git/ChaordicLedger/cachain.zip
        dest: ~/git/lmco/ChaordicLedger/cachain.zip
        mode: '0644'

    - name: Copy registry proxy details
      ansible.builtin.copy:
        src: ~/git/ChaordicLedger/docker_registry_proxy_details.sh
        dest: ~/git/lmco/ChaordicLedger/docker_registry_proxy_details.sh
        mode: '0555'

    - name: Copy GitHub Read Token details
      ansible.builtin.copy:
        src: ~/git/ChaordicLedger/githubReadToken.sh
        dest: ~/git/lmco/ChaordicLedger/githubReadToken.sh
        mode: '0555'

    - name: Execute the setup.
      shell: |
        pwd
        ./reload.sh
      args:
        chdir: ~/git/lmco/ChaordicLedger
      register: result
      check_mode: false
      changed_when: false
      failed_when: result.rc != 0
