apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-data-volume
spec:
  volumeName: ipfs-data-volume
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-export-volume
spec:
  volumeName: ipfs-export-volume
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
