- import_playbook: curl.yml

- hosts: all
  become: yes
  gather_facts: no
  
  vars:
    proxy_env:
      http_proxy: '{{ lookup("env", "http_proxy") }}'
      https_proxy: '{{ lookup("env", "https_proxy") }}'
      no_proxy: '{{ lookup("env", "no_proxy") }}'

  tasks:
    - name: Download helm retrieval script.
      shell:
        cmd: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      register: result
      check_mode: false
      changed_when: false
      failed_when: result.rc != 0

    - name: Set script as executable.
      shell:
        cmd: chmod 700 get_helm.sh
      register: result
      check_mode: false
      changed_when: false
      failed_when: result.rc != 0

    - name: Execute helm retrieval.
      shell:
        cmd: ./get_helm.sh
      register: result
      check_mode: false
      changed_when: false
      failed_when: result.rc != 0

    - name: Check helm is accessible.
      shell:
        cmd: helm version
      register: result
      check_mode: false
      changed_when: false
      failed_when: result.rc != 0
