- hosts: all
  become: yes
  gather_facts: no
  
  vars:
    proxy_env:
      http_proxy: '{{ lookup("env", "http_proxy") }}'
      https_proxy: '{{ lookup("env", "https_proxy") }}'
      no_proxy: '{{ lookup("env", "no_proxy") }}'

  tasks:
    - name: Download kind
      ansible.builtin.get_url:
        url: https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        dest: /usr/bin/kind
        mode: '0555'

    - name: Check kind accessibility
      shell: |
        kind --version
      register: result
      check_mode: false
      changed_when: false
      failed_when: result.rc != 0
