- import_playbook: curl.yml

- hosts: all
  become: yes
  gather_facts: no
  
  vars:
    proxy_env:
      http_proxy: '{{ lookup("env", "http_proxy") }}'
      https_proxy: '{{ lookup("env", "https_proxy") }}'
      no_proxy: '{{ lookup("env", "no_proxy") }}'

  tasks:
    - name: Install requests module.
      shell:
        cmd: pip3 install requests
      register: result
      check_mode: false
      changed_when: false
      failed_when: result.rc != 0

    - name: Install graphviz module.
      shell:
        cmd: pip3 graphviz requests
      register: result
      check_mode: false
      changed_when: false
      failed_when: result.rc != 0
